Fakeinsta/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import Login

urlpatterns = [
    path('', Login.as_view()),
    path('admin/', admin.site.urls),
    path(
        'app/',
        include('app.urls'), )
]

app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'app'

urlpatterns = [
    path(
        'logout/',
        auth_views.logout, {'next_page': 'app:login'},
        name='logout'),
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('feed/', views.Feed.as_view(), name='feed'),
    path('upload/', views.Upload.as_view(), name='upload'),
    path('uploadvideo/', views.Upload_Video.as_view(), name='uploadvideo'),
    path('filter/<doc_id>/', views.Filter.as_view(), name='filter'),
    path('rotate/<doc_id>/', views.Rotate.as_view(), name='rotate'),
    path('delete/<doc_id>/', views.Delete_Picture.as_view(), name='delete'),
    path(
        'deletevideo/<doc_id>/',
        views.Delete_Video.as_view(),
        name='deletevideo'),
    path(
        'comment/<document_id>/', views.Add_Comment.as_view(), name='comment'),
    path(
        'commentvideo/<document_id>/',
        views.Add_Comment_Video.as_view(),
        name='commentvideo'),
    path('likepic/<doc_id>/', views.Like_Pic.as_view(), name='likepic'),
    path('likevideo/<doc_id>/', views.Like_Vid.as_view(), name='likevideo'),
    path(
        'dislikepic/<doc_id>/', views.DisLike_Pic.as_view(),
        name='dislikepic'),
    path(
        'dislikevideo/<doc_id>/',
        views.DisLike_Vid.as_view(),
        name='dislikevideo'),
    path('mostpop/', views.Mostpop.as_view(), name='mostpop'),
    path('bytopic/<topic>/', views.ByTopic.as_view(), name='bytopic'),
    path('search/', views.GetUserPost.as_view(), name='search'),
    path('bycomment/', views.ByComments.as_view(), name='bycomment')
]

app/templates/app/filter.html
{% block body %} {% load static %}

<head>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'app/favicon/favicon.png'%}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/bootwatch.css' %}">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>
<div>
    <center>
        <h2>
            <a href="{% url 'app:feed' %}" class="font-type">Back To Feed Page</a>
        </h2>
        <img src="{% static path %}" width="420">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </center>
</div>
{% endblock %}

app/templates/app/login.html
<html>
{% load static %} {% load app_extras%}

<head>
    <title>FakeInsta</title>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/bootwatch.css' %}">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>

<body>
    <center>
        <div class="container">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Login Page</h2>

                <form action="{% url 'app:login' %}" method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>

                <h1>If Not User Click Button Below.</h1>


                <form action="{% url 'app:signup' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">SignUp</button>
                </form>

            </div>
        </div>
    </center>
</body>

</html>

app/templates/app/signup.html
<html>
{% load static %} {% load app_extras%}

<head>
    <title>FakeInsta</title>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'app/favicon/favicon.png'%}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/bootwatch.css' %}">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>

<body>
    <center>
        <h2>Sign up</h2>
        <form action="{% url 'app:signup' %}" method="post">
            {% csrf_token %} {% for field in form %}
            <p>
                {{ field.label_tag }}
                <br> {{ field }} {% if field.help_text %}
                <!-- <small style="color: black">{{ field.help_text }}</small> -->
                {% endif %} {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
    </center>
</body>

</html>

app/templates/app/upload.html
{% load static %}{% block body %}

<head>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'app/favicon/favicon.png'%}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/bootwatch.css' %}">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>
<div class="container">
    <center>
        <div class="col-lg-12 icon-header">
            <span class="head-text">
                <a href="{% url 'app:feed' %}" class="font-type">Back To Feed Page</a>
            </span>
            <span class="fa-stack fa-md">
                <i class="fa fa-circle fa-stack-1x jotext"></i>
                <i class="fa fa-instagram fa-stack-2x fa-rotate-90" aria-hidden="true"></i>
            </span>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{form}}
            <img id="preview-img" src="#" alt="No Image" />
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </center>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'app/index.js' %}"></script> {% endblock %}

app/templates/app/uploadvideo.html
{% load static %}{% block body %}

<head>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'app/favicon/favicon.png'%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'app/favicon/favicon.png'%}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'app/bootwatch.css' %}">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
</head>
<div class="container">
    <center>
        <div class="col-lg-12 icon-header">
            <span class="head-text">
                <a href="{% url 'app:feed' %}" class="font-type">Back To Feed Page</a>
            </span>
            <span class="fa-stack fa-md">
                <i class="fa fa-circle fa-stack-1x jotext"></i>
                <i class="fa fa-instagram fa-stack-2x fa-rotate-90" aria-hidden="true"></i>
            </span>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{ form}}
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </center>
</div>
{% endblock %}